# Generated by Django 3.1.4 on 2021-01-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0002_auto_20210112_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='title',
            field=models.CharField(default='Bakı şəhərində tam təmirli həyət evi', max_length=45),
            preserve_default=False,
        ),
    ]
