# Generated by Django 3.1.4 on 2021-01-14 03:43

from django.db import migrations, models
import django.db.models.deletion
import rentApp1.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0003_elan_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.RemoveField(
            model_name='elan',
            name='imageAlbum',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='rentApp1.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elan',
            name='image1',
            field=models.ImageField(default='header', upload_to=rentApp1.models.get_post_img_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elan',
            name='image2',
            field=models.ImageField(default='header', upload_to=rentApp1.models.get_post_img_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elan',
            name='image3',
            field=models.ImageField(default='header', upload_to=rentApp1.models.get_post_img_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elan',
            name='image4',
            field=models.ImageField(default='header', upload_to=rentApp1.models.get_post_img_upload_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
