# Generated by Django 3.1.4 on 2021-01-16 08:51

from django.db import migrations, models
import django.db.models.deletion
import rentApp1.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0004_auto_20210114_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='elan',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='elan',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='elan',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='elan',
            name='image4',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rentApp1.models.get_post_img_upload_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentApp1.album')),
            ],
        ),
        migrations.AddField(
            model_name='elan',
            name='imageAlbum',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentApp1.album'),
        ),
    ]
