# Generated by Django 3.1.4 on 2021-01-16 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0005_auto_20210116_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='area',
            field=models.DecimalField(decimal_places=2, default='234', max_digits=20, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elan',
            name='isFlat',
            field=models.CharField(choices=[('flat', 'Mənzil'), ('apartment', 'Həyət evi')], default='flat', max_length=50),
        ),
    ]
