# Generated by Django 3.1.4 on 2021-01-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0006_auto_20210116_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='location_lat',
            field=models.CharField(default='sss', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elan',
            name='location_lng',
            field=models.CharField(default='sss', max_length=100),
            preserve_default=False,
        ),
    ]
