# Generated by Django 3.1.4 on 2021-01-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0008_auto_20210119_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elan',
            old_name='imageAlbum',
            new_name='image_album',
        ),
    ]
