# Generated by Django 3.1.4 on 2021-01-25 12:05

from django.db import migrations, models
import rentApp1.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0009_auto_20210119_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=rentApp1.models.get_pfp_upload_path),
        ),
    ]
