# Generated by Django 3.1.4 on 2021-01-26 18:43

from django.db import migrations, models
import django.db.models.deletion
import rentApp1.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0011_comment_image_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=rentApp1.models.get_post_img_upload_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentApp1.album')),
            ],
        ),
    ]
