# Generated by Django 3.1.4 on 2021-01-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0012_commentimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentImages',
            new_name='CommentImage',
        ),
    ]
