# Generated by Django 3.1.4 on 2021-01-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0013_auto_20210126_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='comment_count',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elan',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
