# Generated by Django 3.1.4 on 2021-01-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0014_auto_20210128_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elan',
            name='isRent',
            field=models.CharField(choices=[('Kirayə', (('Daily', 'Günlük'), ('Monthly', 'Aylıq'))), ('sale', 'Satış')], default='Daily', max_length=50),
        ),
    ]
