# Generated by Django 3.1.4 on 2021-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0016_auto_20210128_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elan',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default='Rəy yoxdur', max_digits=2, null=True),
        ),
    ]
