# Generated by Django 3.1.4 on 2021-02-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0017_auto_20210202_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='not_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='elan',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='elan',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
