# Generated by Django 3.1.4 on 2021-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0018_auto_20210203_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+994513411979', max_length=17),
            preserve_default=False,
        ),
    ]
