# Generated by Django 3.1.4 on 2021-02-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp1', '0020_comment_not_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
